# Generated by Django 4.2.6 on 2023-10-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Bitcoin.svg.png', upload_to='profile_images')),
                ('win_rate', models.FloatField(default=0.0)),
                ('bio', models.TextField()),
                ('failed_trades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_failed_trades', to='history.trade')),
                ('successful_trades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_successful_trades', to='history.trade')),
                ('total_trades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_total_trades', to='history.trade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
