# Generated by Django 4.2.6 on 2023-10-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_day', models.ImageField(upload_to='charts/day')),
                ('chart_hour', models.ImageField(upload_to='charts/hour')),
                ('chart_close', models.ImageField(upload_to='charts/close')),
                ('trade_type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_price', models.FloatField()),
                ('stop', models.FloatField()),
                ('tp_1', models.FloatField()),
                ('tp_2', models.FloatField(blank=True)),
                ('profit_or_loss', models.FloatField()),
                ('trade_result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
